name: Update npm packages
description: |
  Update npm packages.

  Use this as part of your workflow, e.g. on a daily schedule.
branding:
  icon: arrow-up-circle
  color: green

runs:
  using: composite
  steps:
    - name: Update dependenci¬es
      run: echo 'such update! very new! wow!'
      shell: bash
  post-if: success()
  post: echo git commit
